language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t brandonessex/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true brandonessex/docker-react npm run test